version: '3'
services:
  java-srv:
    build:
      context: java-srv
    depends_on:
      - db
    links:
      - "db:db"
    volumes:
      - ./java-srv/log:/root/log

  db:
    build: db
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=animal
      - POSTGRES_USER=maria
      - POSTGRES_PASSWORD=pass
